name: test
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  apt_update_apt_upgrade:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: apt_update
        run: sudo apt update
      - name: apt_upgrade
        run: sudo apt upgrade
      - name: clone repository
        uses: actions/checkout@v3
      - name: check clone
        run: ls -la
