name: test
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  install_htop:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: install htop
        run: sudo apt install htop
